/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrophiesRouteImport } from './routes/trophies'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RealityRouteImport } from './routes/reality'
import { Route as PetRouteImport } from './routes/pet'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FutureRouteImport } from './routes/future'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TrophiesRoute = TrophiesRouteImport.update({
  id: '/trophies',
  path: '/trophies',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RealityRoute = RealityRouteImport.update({
  id: '/reality',
  path: '/reality',
  getParentRoute: () => rootRouteImport,
} as any)
const PetRoute = PetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/future': typeof FutureRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/pet': typeof PetRoute
  '/reality': typeof RealityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/trophies': typeof TrophiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/future': typeof FutureRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/pet': typeof PetRoute
  '/reality': typeof RealityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/trophies': typeof TrophiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/future': typeof FutureRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/pet': typeof PetRoute
  '/reality': typeof RealityRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/trophies': typeof TrophiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avatar'
    | '/future'
    | '/goals'
    | '/habits'
    | '/journal'
    | '/onboarding'
    | '/pet'
    | '/reality'
    | '/settings'
    | '/shop'
    | '/track'
    | '/trophies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avatar'
    | '/future'
    | '/goals'
    | '/habits'
    | '/journal'
    | '/onboarding'
    | '/pet'
    | '/reality'
    | '/settings'
    | '/shop'
    | '/track'
    | '/trophies'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/avatar'
    | '/future'
    | '/goals'
    | '/habits'
    | '/journal'
    | '/onboarding'
    | '/pet'
    | '/reality'
    | '/settings'
    | '/shop'
    | '/track'
    | '/trophies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AvatarRoute: typeof AvatarRoute
  FutureRoute: typeof FutureRoute
  GoalsRoute: typeof GoalsRoute
  HabitsRoute: typeof HabitsRoute
  JournalRoute: typeof JournalRoute
  OnboardingRoute: typeof OnboardingRoute
  PetRoute: typeof PetRoute
  RealityRoute: typeof RealityRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TrackRoute: typeof TrackRoute
  TrophiesRoute: typeof TrophiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trophies': {
      id: '/trophies'
      path: '/trophies'
      fullPath: '/trophies'
      preLoaderRoute: typeof TrophiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reality': {
      id: '/reality'
      path: '/reality'
      fullPath: '/reality'
      preLoaderRoute: typeof RealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet': {
      id: '/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AvatarRoute: AvatarRoute,
  FutureRoute: FutureRoute,
  GoalsRoute: GoalsRoute,
  HabitsRoute: HabitsRoute,
  JournalRoute: JournalRoute,
  OnboardingRoute: OnboardingRoute,
  PetRoute: PetRoute,
  RealityRoute: RealityRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TrackRoute: TrackRoute,
  TrophiesRoute: TrophiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
